theme: jekyll-theme-minimal
title: Diata Traore's page
substitle: PhD candidate at Laboratoire de Chimie Théorique (Sorbonne Université - France)
description: Research works on development of methods for corrections of wave-function calculations for electronic structure usingdensity functional approximations.
