theme: jekyll-theme-minimal
title: Diata Traore's page
description: Research works on development of methods for corrections of wave-function calculations for electronic structure using density functional approximations.
